### ISSUE TITLE
Issues in creating binary for Linux platforms

### ISSUE THREAD

**Issue by ahmadfaiz93** [facebookincubator/marketing-data-file-uploader#10]
I want to save MDFU as an executable on both the Linux and Windows platform. The details for these are given below:

- Windows 7 Enterprise, 32 bit operating system

- Server running Linux el6.x86_64

I am working with MDFU on Windows environment and the need to generate binaries to be run on Linux.

The problem is with the file type generated. Using both "npm run build-binary" and "npm run build-binary-exe" the file format of the executable generated remains the same which is windows based. Also there I could not find any option to specify the target machine while creating the binary using MDFU. 

![mdfu_build_err](https://user-images.githubusercontent.com/33657523/33031247-b5081668-ce43-11e7-8de5-a9cc664bd2f8.PNG)

I also tried downloading NEXE separately and then bundling into an exe. This resulted in the correct file format but I got other errors related to installation of dependency . 

I finally had a workaround by using [PKG](https://github.com/zeit/pkg). This enabled to generate the correct executable running under the Linux environment. 

I think the issue is in creating executable for other platforms. This is because the executable generated using MDFU works as expected under Windows. However, we have issues with regards to creating Linux based executable from a Windows machine. 

Please let me know if this requires some change in the MDFU package or some corrections from my end in creating the required binaries.

**Comment by bob1th** [comment]
Hello, MDFU currently does not support creating binaries for platforms other than the platform you are running the build script on.   To generate the linux binary, the best route would be installing MDFU package on a linux box and run the build script.  Thanks and sorry for the inconveniences.
