### ISSUE TITLE
Non-Purchase Events?

### ISSUE THREAD

**Issue by robertocarloscalderon** [facebookincubator/marketing-data-file-uploader#14]
Is the MDFU capable of uploading non-purchase events? I'm trying to upload events as "Other," but want to verify. It's a handy tool and would like to be able to use it for other standard event types:

- "ViewContent"
- "Search"
- "AddToCart"
- "AddToWishlist"
- "InitiateCheckout"
- "AddPaymentInfo"
- "Lead"
- "CompleteRegistration"
- "Other"

**Comment by bob1th** [comment]
Yes.  These events can be uploaded.
